building evc pipeline
UKHomeOffice/evc pull request #1
Opened 2024-07-12 16:00 UTC by DivineTaminangHO

# WHAT ?
Pipeline for EVC
E-visa Contact Us is a form for members of the public to contact the home office regarding their e-visa

# WHY ?
This pipeline will allow for the applications to be developed in or to enable applicant to contact the home office

2024-07-18 13:01 UTC, adityababumallisettiHO commented
Can you also add sonarqube properties file please

2024-07-18 16:45 UTC, adityababumallisettiHO requested changes

2024-07-18 16:48 UTC, DivineTaminangHO commented on .drone.yml
> +  #IMAGE_URL:
done

2024-07-18 17:01 UTC, DivineTaminangHO commented on .drone.yml
> +        from_secret: slack_webhook
yes, these are from coa and I already have the slack_webhook configured In drone UI

2024-07-18 17:19 UTC, DivineTaminangHO commented on .drone.yml
> +      #repo: ${IMAGE_REPO}
resolved

2024-07-18 17:19 UTC, DivineTaminangHO commented on .drone.yml
> +        from_secret: slack_webhook
resolved

2024-07-18 17:19 UTC, DivineTaminangHO commented on .drone.yml
> +        from_secret: slack_webhook
resolved

2024-07-19 08:31 UTC, adityababumallisettiHO approved these changes
lgtm

2024-07-19 09:34 UTC, merged